### ISSUE TITLE
Overwrites vscode commands by default

### ISSUE THREAD

**Issue by AndrewRayCode** [noku/rails-run-spec-vscode#14]
command-shift-t undoes the last closed tab, and this plugin overwrites it, with no way to undo the mapping except to manually fix the original mapping and remap a new key command

**Comment by JoshAddington** [comment]
This is a dealbreaker

**Comment by sekmo** [comment]
I totally agree, but you can also fix it by yourself just changing the keyboard mapping.

**Comment by laurmurclar** [comment]
Is this repo still accepting PRs @noku? I'd like to work on a fix for this issue if so.

**Comment by noku** [comment]
@laurmurclar yes it does

**Comment by solipet** [comment]
While you're in there Cmd-L (runSpecLine) overrides the builtin `expandLineSelection`, i.e., select the current line. 🙂
