### ISSUE TITLE
Path to spec file incorrect when using workspaces

### ISSUE THREAD

**Issue by mFingers** [noku/rails-run-spec-vscode#15]
Using the newly introduced VSCode workspaces, when using `CMD+L`, the terminal opens to the correct root directory, but the path to the spec also contains the root directory, so the spec file doesn't load.

For example, I have a workspace with two root folders:
- Root1
- Root2
  - spec
    - feature.spec.rb

If I have `feature.spec.rb` open, and go to run the specs, the terminal opens to `~/.../Root2/`, and the path for the spec file will be `Root2/spec/feature.spec.rb`.  Instead, it should be `spec/feature.spec.rb`.

**Comment by sekmo** [comment]
Looks like still happening? Fresh install of VS Code and extension :(
Any suggestions about what to check?
