### ISSUE TITLE
Run File Spec ignores/removes the lib directory

### ISSUE THREAD

**Issue by brand-it** [noku/rails-run-spec-vscode#16]
The command `>Run file Spec` has bit of a problem lib directories. It removes the word lib from the file path. The file that it is going to test is called `lib/external/client.rb`

What the command above gives me
```shell
$ bundle exec rspec spec/external/client_spec.rb
```

What the command should look like
```shell
$ bundle exec rspec spec/lib/external/client_spec.rb 
```

**Comment by newdark** [comment]
OH right forgot you have to run that command from the file that you want to test. In this case above it is `lib/external/client.rb`

**Comment by wasabigeek** [comment]
Also ran into this issue, I think the extension follows rspec-rail's suggested spec location by default: https://relishapp.com/rspec/rspec-rails/v/3-8/docs/directory-structure (/app and /lib are condensed into the /specs folder). Not sure yet how to go around this

**Comment by wasabigeek** [comment]
@noku what do you think of including customisable fallback paths as a way around this? e.g. if /spec/example_spec.rb doesn't work, try /spec/lib/example_spec.rb

I can have a shot at that if you think that's a good way to handle it.
