### ISSUE TITLE
Console shows prompt directly after run

### ISSUE THREAD

**Issue by nicolas-heinig** [noku/rails-run-spec-vscode#20]
Hi,

first of all thanks for making this extension, it saved me a lot of time.

I have a problem with the tasks since I upgraded vscode to 1.23:

Right after I ran one of the tasks, the integrated console shows me my prompt at the top of the window, so I cannot see the results of the tests.

Could be that I have some misconfiguration here. I can provide my config if necessary.

Thanks for the help,

Nick

**Comment by Hbbb** [comment]
I am experiencing the same issue.

VSCode Version: `1.23.0`
Extension Version: `0.1.1`

Here's what it looks like:
![clearing_spec_results](https://user-images.githubusercontent.com/3803272/39821734-dac5801c-5376-11e8-8d1a-8dda6e7bd42b.gif)

Forgive that slow spec startup time 😅

**Comment by noku** [comment]
@nicolas-heinig @Hbbb I have published a fix for the issue. 

The update updated the extension version is `0.1.2`. PTAL. Hope it helps resolve the issue.

**Comment by Hbbb** [comment]
@noku Fantastic! I updated to `0.1.2` and the issue is resolved. I'm curious, when did `vscode.commands.executeCommand('workbench.action.terminal.clear')` become async?

**Comment by nicolas-heinig** [comment]
@noku Awesome! Thank you very much 🎉
