### ISSUE TITLE
add Run Folder Specs

### ISSUE THREAD

**Issue by frostmark** [noku/rails-run-spec-vscode#3]
add ability of run specs for folder. I think it is necessary function :)

**Comment by noku** [comment]
hi @frostmark I implemented this as following. From the side bar you can right click on a **folder** or a file and choose `Run Specs` options.

![screen shot 2017-02-07 at 11](https://cloud.githubusercontent.com/assets/2285726/22713037/8c4648b6-ed8f-11e6-84fb-9f2b59a44012.png)

**Comment by frostmark** [comment]
@noku hi, it's good. thx
