### ISSUE TITLE
Running the contributed command:'extension.runFileSpecs' failed.

### ISSUE THREAD

**Issue by jcw-** [noku/rails-run-spec-vscode#6]
This started occurring after upgrading to VS Code 1.10.1 (Mac) when I execute the Run File Specs command. There is no output in Debug Console or Output -> Extensions. Having the terminal window open in advance doesn't help either.

I'm guessing this is related to terminal window changes in the latest release of VS Code.

**Comment by noku** [comment]
@jcw- Thanks for submitting this, I pushed a fix, should be available. (version `0.0.9`).

**Comment by jcw-** [comment]
Confirmed working - thanks for the fast response!
