### ISSUE TITLE
Automatically save file before running specs?

### ISSUE THREAD

**Issue by suan** [noku/rails-run-spec-vscode#8]
I often forget to save the current file (code or spec file) before using the keyboard shortcuts to run the spec(s) - would u consider a feature which first automatically saves the current file?

**Comment by nolanpro** [comment]
@suan if you have `"files.autoSave": "onFocusChange"` and `"ruby.specFocusTerminal": true` it will save the file before running. Unfortunately, I don't want to focus the terminal.

@noku Thanks for this great extension. It would be great to have this option

**Comment by noku** [comment]
@suan @nolanpro I have added a new configuration option `"ruby.specSaveFile"`, by default `false`.
If you turn it on, it will save the spec file before running spec tests.

PS: Sorry that it took so long to implement.

**Comment by nolanpro** [comment]
Awesome thanks!
